export const GET_ALL_EMPLOYEES = 'GET_ALL_EMPLOYEES';

export const GET_URL = 'GET_URL';

export const SET_AUTHENTICATED_USER = 'SET_AUTHENTICATED_USER';

export const SET_SESSION_EXPIRE = 'SET_SESSION_EXPIRE';

export const GET_ONE_EMPLOYEE = 'GET_ONE_EMPLOYEE'

export const GET_ALL_BOOKINGS = 'GET_ALL_BOOKINGS';

export const GET_ONE_GUEST = 'GET_ONE_GUEST';

export const GET_ALL_ROOMS = 'GET_ALL_ROOMS';

export const GET_ONE_ROOM = 'GET_ONE_ROOM';

export const GET_ALL_ROOM_TYPES = 'GET_ALL_ROOM_TYPES';

export const GET_ONE_ROOMTYPE = 'GET_ONE_ROOMTYPE';

export const GET_AVAILABLE_ROOMS = 'GET_AVAILABLE_ROOMS';