export const GET_ALL_EMPLOYEES = 'GET_ALL_EMPLOYEES';

export const GET_URL = 'GET_URL';

export const SET_AUTHENTICATED_USER = 'SET_AUTHENTICATED_USER';

export const SET_SESSION_EXPIRE = 'SET_SESSION_EXPIRE';

export const GET_ONE_EMPLOYEE = 'GET_ONE_EMPLOYEE'

export const GET_ALL_BOOKINGS = 'GET_ALL_BOOKINGS';

export const GET_ALL_CUSTOMER_BOOKINGS = 'GET_ALL_CUSTOMER_BOOKINGS';

export const GET_ONE_GUEST = 'GET_ONE_GUEST';

export const GET_ALL_ROOMS = 'GET_ALL_ROOMS';

export const GET_ONE_ROOM = 'GET_ONE_ROOM';

export const GET_ALL_ROOM_TYPES = 'GET_ALL_ROOM_TYPES';

export const GET_ONE_ROOMTYPE = 'GET_ONE_ROOMTYPE';

export const GET_AVAILABLE_ROOMS = 'GET_AVAILABLE_ROOMS';

export const GET_SELECTED_ROOM = 'GET_SELECTED_ROOM';

export const GET_SELECTED_ROOM_DETAILS = 'GET_SELECTED_ROOM_DETAILS';

export const GET_SELECTED_ROOM_NUMBER = 'GET_SELECTED_ROOM_NUMBER';

export const GET_GUEST_ID = 'GET_GUEST_ID';

export const GET_ALL_GUESTS = 'GET_ALL_GUESTS';

export const GET_ALL_MESSAGES = 'GET_ALL_MESSAGES';

export const GET_BOOKING_ID = 'GET_BOOKING_ID';

export const GET_BOOKING_ID_DETAILS = 'GET_BOOKING_ID_DETAILS';

export const GET_ONE_GUEST_DETAILS = 'GET_ONE_GUEST_DETAILS';

export const GET_SELECTED_DATES = 'GET_SELECTED_DATES';

export const CHECK_AVAILABLE_ROOMS = 'CHECK_AVAILABLE_ROOMS';

export const RESET_CHECK_AVAILABLE_ROOMS = 'RESET_CHECK_AVAILABLE_ROOMS';

export const GET_AVAILABLE_ROOM_NUMBER = 'GET_AVAILABLE_ROOM_NUMBER';
